CREATE TABLE projects (
id INTEGER PRIMARY KEY,
name TEXT,
age INTEGER,
breed TEXT);

CREATE TABLE users (
id INTEGER PRIMARY KEY,
name TEXT,
age INTEGER,
breed TEXT);

CREATE TABLE pledges (
id INTEGER PRIMARY KEY,
name TEXT,
age INTEGER,
breed TEXT);
